### ISSUE TITLE
Traceback (most recent call last):  (ему  лень работать)

### ISSUE THREAD

**Issue by LixaSl** [hristonbtw/tg-autoresponder#1]
File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\updates.py", line 483, in _dispatch_update
    await callback(event)
  File "C:\Users\Влад\Desktop\tg-autoresponder-main\main.py", line 23, in normal_handler
    voc = json.load(file)
          ^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 74 (char 134)
Unhandled exception on normal_handler
Traceback (most recent call last):
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\updates.py", line 483, in _dispatch_update
    await callback(event)
  File "C:\Users\Влад\Desktop\tg-autoresponder-main\main.py", line 23, in normal_handler
    voc = json.load(file)
          ^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Влад\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 74 (char 134)

**Comment by hristonbtw** [comment]
Если исходить из ошибки, то судя по всему проблема заключается в вашем словаре.
